# Generated by Django 5.0.6 on 2024-05-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('uni_email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leasing.user')),
            ],
            bases=('leasing.user',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('street_01', models.CharField(max_length=30)),
                ('street_02', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=7)),
                ('province', models.CharField(max_length=2)),
                ('university', models.CharField(max_length=50)),
                ('prop_type', models.CharField(max_length=20)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('term', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.user')),
            ],
        ),
    ]
